package iso3162

type ID int

const (
	ID_None ID = iota
	ID_Andorra
	ID_United_Arab_Emirates
	ID_Afghanistan
	ID_Antigua_And_Barbuda
	ID_Anguilla
	ID_Albania
	ID_Armenia
	ID_Angola
	ID_Antarctica
	ID_Argentina
	ID_American_Samoa
	ID_Austria
	ID_Australia
	ID_Aruba
	ID_Aland_Islands
	ID_Azerbaijan
	ID_Bosnia_And_Herzegovina
	ID_Barbados
	ID_Bangladesh
	ID_Belgium
	ID_Burkina_Faso
	ID_Bulgaria
	ID_Bahrain
	ID_Burundi
	ID_Benin
	ID_Saint_Barthelemy
	ID_Bermuda
	ID_Brunei_Darussalam
	ID_Bolivia
	ID_Bonaire
	ID_Brazil
	ID_Bahamas
	ID_Bhutan
	ID_Bouvet_Island
	ID_Botswana
	ID_Belarus
	ID_Belize
	ID_Canada
	ID_Cocos_Islands
	ID_Congo_Democratic_Republic_Of
	ID_Central_African_Republic
	ID_Congo
	ID_Switzerland
	ID_Cote_d_Ivoire
	ID_Cook_Islands
	ID_Chile
	ID_Cameroon
	ID_China
	ID_Colombia
	ID_Costa_Rica
	ID_Cuba
	ID_Cabo_Verde
	ID_Curacao
	ID_Christmas_Island
	ID_Cyprus
	ID_Czechia
	ID_Germany
	ID_Djibouti
	ID_Denmark
	ID_Dominica
	ID_Dominican_Republic
	ID_Algeria
	ID_Ecuador
	ID_Estonia
	ID_Egypt
	ID_Western_Sahara
	ID_Eritrea
	ID_Spain
	ID_Ethiopia
	ID_Finland
	ID_Fiji
	ID_Falkland_Islands
	ID_Micronesia
	ID_Faroe_Islands
	ID_France
	ID_Gabon
	ID_United_Kingdom
	ID_Grenada
	ID_Georgia
	ID_French_Guiana
	ID_Guernsey
	ID_Ghana
	ID_Gibraltar
	ID_Greenland
	ID_Gambia
	ID_Guinea
	ID_Guadeloupe
	ID_Equatorial_Guinea
	ID_Greece
	ID_South_Georgia_And_South_Sandwich_Islands
	ID_Guatemala
	ID_Guam
	ID_Guinea_Bissau
	ID_Guyana
	ID_Hong_Kong
	ID_Heard_Island_And_McDonald_Islands
	ID_Honduras
	ID_Croatia
	ID_Haiti
	ID_Hungary
	ID_Indonesia
	ID_Ireland
	ID_Israel
	ID_Isle_Of_Man
	ID_India
	ID_British_Indian_Ocean_Territory
	ID_Iraq
	ID_Iran
	ID_Iceland
	ID_Italy
	ID_Jersey
	ID_Jamaica
	ID_Jordan
	ID_Japan
	ID_Kenya
	ID_Kyrgyzstan
	ID_Cambodia
	ID_Kiribati
	ID_Comoros
	ID_Saint_Kitts_And_Nevis
	ID_North_Korea
	ID_South_Korea
	ID_Kuwait
	ID_Cayman_Islands
	ID_Kazakhstan
	ID_Lao
	ID_Lebanon
	ID_Saint_Lucia
	ID_Liechtenstein
	ID_Sri_Lanka
	ID_Liberia
	ID_Lesotho
	ID_Lithuania
	ID_Luxembourg
	ID_Latvia
	ID_Libya
	ID_Morocco
	ID_Monaco
	ID_Moldova
	ID_Montenegro
	ID_Saint_Martin_French
	ID_Madagascar
	ID_Marshall_Islands
	ID_North_Macedonia
	ID_Mali
	ID_Myanmar
	ID_Mongolia
	ID_Macao
	ID_Northern_Mariana_Islands
	ID_Martinique
	ID_Mauritania
	ID_Montserrat
	ID_Malta
	ID_Mauritius
	ID_Maldives
	ID_Malawi
	ID_Mexico
	ID_Malaysia
	ID_Mozambique
	ID_Namibia
	ID_New_Caledonia
	ID_Niger
	ID_Norfolk_Island
	ID_Nigeria
	ID_Nicaragua
	ID_Netherlands
	ID_Norway
	ID_Nepal
	ID_Nauru
	ID_Niue
	ID_New_Zealand
	ID_Oman
	ID_Panama
	ID_Peru
	ID_French_Polynesia
	ID_Papua_New_Guinea
	ID_Philippines
	ID_Pakistan
	ID_Poland
	ID_Saint_Pierre_And_Miquelon
	ID_Pitcairn
	ID_Puerto_Rico
	ID_Palestine
	ID_Portugal
	ID_Palau
	ID_Paraguay
	ID_Qatar
	ID_Russia
	ID_Rwanda
	ID_Saudi_Arabia
	ID_Solomon_Islands
	ID_Seychelles
	ID_Sudan
	ID_Sweden
	ID_Singapore
	ID_Saint_Helena_Ascension_And_Tristan_Da_Cunha
	ID_Slovenia
	ID_Svalbard_And_Jan_Mayen
	ID_Slovakia
	ID_Sierra_Leone
	ID_San_Marino
	ID_Senegal
	ID_Somalia
	ID_Suriname
	ID_South_Sudan
	ID_Sao_Tome_And_Principe
	ID_El_Salvador
	ID_Sint_Maarten_Dutch
	ID_Syria
	ID_Eswatini
	ID_Turks_And_Caicos_Islands
	ID_Chad
	ID_French_Southern_Territories
	ID_Togo
	ID_Thailand
	ID_Tajikistan
	ID_Tokelau
	ID_Timor_Leste
	ID_Turkmenistan
	ID_Tunisia
	ID_Tonga
	ID_Turkey
	ID_Trinidad_And_Tobago
	ID_Tuvalu
	ID_Taiwan
	ID_Tanzania
	ID_Ukraine
	ID_United_States_Minor_Outlying_Islands
	ID_United_States
	ID_Uruguay
	ID_Uzbekistan
	ID_Holy_See
	ID_Vatican
	ID_Saint_Vincent_And_The_Grenadines
	ID_Venezuela
	ID_Virgin_Islands_British
	ID_Virgin_Islands_US
	ID_Vietnam
	ID_Vanuatu
	ID_Wallis_And_Futuna
	ID_Samoa
	ID_Yemen
	ID_Mayotte
	ID_South_Africa
	ID_Zambia
	ID_Zimbabwe
)
