// [Source]https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes

package iso639

type ID int
type Name string

const (
	CODE_None ID = iota
	CODE_Abkhazian
	CODE_Afar
	CODE_Afrikaans
	CODE_Akan
	CODE_Albanian
	CODE_Amharic
	CODE_Arabic
	CODE_Aragonese
	CODE_Armenian
	CODE_Assamese
	CODE_Avaric
	CODE_Avestan
	CODE_Aymara
	CODE_Azerbaijani
	CODE_Bambara
	CODE_Bashkir
	CODE_Basque
	CODE_Belarusian
	CODE_Bengali
	CODE_Bislama
	CODE_Bosnian
	CODE_Breton
	CODE_Bulgarian
	CODE_Burmese
	CODE_Catalan
	CODE_Valencian
	CODE_Chamorro
	CODE_Chechen
	CODE_Chichewa
	CODE_Chewa
	CODE_Nyanja
	CODE_Chinese
	CODE_Church_Slavonic
	CODE_Old_Slavonic
	CODE_Old_Church_Slavonic
	CODE_Chuvash
	CODE_Cornish
	CODE_Corsican
	CODE_Cree
	CODE_Croatian
	CODE_Czech
	CODE_Danish
	CODE_Divehi
	CODE_Dhivehi
	CODE_Maldivian
	CODE_Dutch
	CODE_Flemish
	CODE_Dzongkha
	CODE_English
	CODE_Esperanto
	CODE_Estonian
	CODE_Ewe
	CODE_Faroese
	CODE_Fijian
	CODE_Finnish
	CODE_French
	CODE_Western_Frisian
	CODE_Fulah
	CODE_Gaelic
	CODE_Scottish_Gaelic
	CODE_Galician
	CODE_Ganda
	CODE_Georgian
	CODE_German
	CODE_Greek
	CODE_Kalaallisut
	CODE_Greenlandic
	CODE_Guarani
	CODE_Gujarati
	CODE_Haitian
	CODE_Haitian_Creole
	CODE_Hausa
	CODE_Hebrew
	CODE_Herero
	CODE_Hindi
	CODE_Hiri_Motu
	CODE_Hungarian
	CODE_Icelandic
	CODE_Ido
	CODE_Igbo
	CODE_Indonesian
	CODE_Interlingua
	CODE_Interlingue
	CODE_Occidental
	CODE_Inuktitut
	CODE_Inupiaq
	CODE_Irish
	CODE_Italian
	CODE_Japanese
	CODE_Javanese
	CODE_Kannada
	CODE_Kanuri
	CODE_Kashmiri
	CODE_Kazakh
	CODE_Central_Khmer
	CODE_Kikuyu
	CODE_Gikuyu
	CODE_Kinyarwanda
	CODE_Kirghiz
	CODE_Kyrgyz
	CODE_Komi
	CODE_Kongo
	CODE_Korean
	CODE_Kuanyama
	CODE_Kwanyama
	CODE_Kurdish
	CODE_Lao
	CODE_Latin
	CODE_Latvian
	CODE_Limburgan
	CODE_Limburger
	CODE_Limburgish
	CODE_Lingala
	CODE_Lithuanian
	CODE_Luba_Katanga
	CODE_Luxembourgish
	CODE_Letzeburgesch
	CODE_Macedonian
	CODE_Malagasy
	CODE_Malay
	CODE_Malayalam
	CODE_Maltese
	CODE_Manx
	CODE_Maori
	CODE_Marathi
	CODE_Marshallese
	CODE_Mongolian
	CODE_Nauru
	CODE_Navajo
	CODE_Navaho
	CODE_North_Ndebele
	CODE_South_Ndebele
	CODE_Ndonga
	CODE_Nepali
	CODE_Norwegian
	CODE_Norwegian_Bokmal
	CODE_Norwegian_Nynorsk
	CODE_Sichuan_Yi
	CODE_Nuosu
	CODE_Occitan
	CODE_Ojibwa
	CODE_Oriya
	CODE_Oromo
	CODE_Ossetian
	CODE_Ossetic
	CODE_Pali
	CODE_Pashto
	CODE_Pushto
	CODE_Persian
	CODE_Polish
	CODE_Portuguese
	CODE_Punjabi
	CODE_Panjabi
	CODE_Quechua
	CODE_Romanian
	CODE_Moldavian
	CODE_Moldovan
	CODE_Romansh
	CODE_Rundi
	CODE_Russian
	CODE_Northern_Sami
	CODE_Samoan
	CODE_Sango
	CODE_Sanskrit
	CODE_Sardinian
	CODE_Serbian
	CODE_Shona
	CODE_Sindhi
	CODE_Sinhala
	CODE_Sinhalese
	CODE_Slovak
	CODE_Slovenian
	CODE_Somali
	CODE_Southern_Sotho
	CODE_Spanish
	CODE_Castilian
	CODE_Sundanese
	CODE_Swahili
	CODE_Swati
	CODE_Swedish
	CODE_Tagalog
	CODE_Tahitian
	CODE_Tajik
	CODE_Tamil
	CODE_Tatar
	CODE_Telugu
	CODE_Thai
	CODE_Tibetan
	CODE_Tigrinya
	CODE_Tonga
	CODE_Tsonga
	CODE_Tswana
	CODE_Turkish
	CODE_Turkmen
	CODE_Twi
	CODE_Uighur
	CODE_Uyghur
	CODE_Ukrainian
	CODE_Urdu
	CODE_Uzbek
	CODE_Venda
	CODE_Vietnamese
	CODE_Volapuk
	CODE_Walloon
	CODE_Welsh
	CODE_Wolof
	CODE_Xhosa
	CODE_Yiddish
	CODE_Yoruba
	CODE_Zhuang
	CODE_Chuang
	CODE_Zulu
)
