package names

import (
	"strings"

	"github.com/joaoribeirodasilva/countries_info/iso639"
)

type ID int
type Name string

var names = map[iso639.ID]Name{
	iso639.CODE_None:                "None",
	iso639.CODE_Abkhazian:           "Abkhazian",
	iso639.CODE_Afar:                "Afar",
	iso639.CODE_Afrikaans:           "Afrikaans",
	iso639.CODE_Akan:                "Akan",
	iso639.CODE_Albanian:            "Albanian",
	iso639.CODE_Amharic:             "Amharic",
	iso639.CODE_Arabic:              "Arabic",
	iso639.CODE_Aragonese:           "Aragonese",
	iso639.CODE_Armenian:            "Armenian",
	iso639.CODE_Assamese:            "Assamese",
	iso639.CODE_Avaric:              "Avaric",
	iso639.CODE_Avestan:             "Avestan",
	iso639.CODE_Aymara:              "Aymara",
	iso639.CODE_Azerbaijani:         "Azerbaijani",
	iso639.CODE_Bambara:             "Bambara",
	iso639.CODE_Bashkir:             "Bashkir",
	iso639.CODE_Basque:              "Basque",
	iso639.CODE_Belarusian:          "Belarusian",
	iso639.CODE_Bengali:             "Bengali",
	iso639.CODE_Bislama:             "Bislama",
	iso639.CODE_Bosnian:             "Bosnian",
	iso639.CODE_Breton:              "Breton",
	iso639.CODE_Bulgarian:           "Bulgarian",
	iso639.CODE_Burmese:             "Burmese",
	iso639.CODE_Catalan:             "Catalan",
	iso639.CODE_Valencian:           "Catalan",
	iso639.CODE_Chamorro:            "Chamorro",
	iso639.CODE_Chechen:             "Chechen",
	iso639.CODE_Chichewa:            "Chichewa",
	iso639.CODE_Chewa:               "Chichewa",
	iso639.CODE_Nyanja:              "Chichewa",
	iso639.CODE_Chinese:             "Chinese",
	iso639.CODE_Church_Slavonic:     "Church Slavonic",
	iso639.CODE_Old_Slavonic:        "Old Slavonic",
	iso639.CODE_Old_Church_Slavonic: "Old Church Slavonic",
	iso639.CODE_Chuvash:             "Chuvash",
	iso639.CODE_Cornish:             "Cornish",
	iso639.CODE_Corsican:            "Corsican",
	iso639.CODE_Cree:                "Cree",
	iso639.CODE_Croatian:            "Croatian",
	iso639.CODE_Czech:               "Czech",
	iso639.CODE_Danish:              "Danish",
	iso639.CODE_Divehi:              "Divehi",
	iso639.CODE_Dhivehi:             "Dhivehi",
	iso639.CODE_Maldivian:           "Maldivian",
	iso639.CODE_Dutch:               "Dutch",
	iso639.CODE_Flemish:             "Flemish",
	iso639.CODE_Dzongkha:            "Dzongkha",
	iso639.CODE_English:             "English",
	iso639.CODE_Esperanto:           "Esperanto",
	iso639.CODE_Estonian:            "Estonian",
	iso639.CODE_Ewe:                 "Ewe",
	iso639.CODE_Faroese:             "Faroese",
	iso639.CODE_Fijian:              "Fijian",
	iso639.CODE_Finnish:             "Finnish",
	iso639.CODE_French:              "French",
	iso639.CODE_Western_Frisian:     "Western Frisian",
	iso639.CODE_Fulah:               "Fulah",
	iso639.CODE_Gaelic:              "Gaelic",
	iso639.CODE_Scottish_Gaelic:     "Scottish Gaelic",
	iso639.CODE_Galician:            "Galician",
	iso639.CODE_Ganda:               "Ganda",
	iso639.CODE_Georgian:            "Georgian",
	iso639.CODE_German:              "German",
	iso639.CODE_Greek:               "Greek",
	iso639.CODE_Kalaallisut:         "Kalaallisut",
	iso639.CODE_Greenlandic:         "Greenlandic",
	iso639.CODE_Guarani:             "Guarani",
	iso639.CODE_Gujarati:            "Gujarati",
	iso639.CODE_Haitian:             "Haitian",
	iso639.CODE_Haitian_Creole:      "Haitian",
	iso639.CODE_Hausa:               "Hausa",
	iso639.CODE_Hebrew:              "Hebrew",
	iso639.CODE_Herero:              "Herero",
	iso639.CODE_Hindi:               "Hindi",
	iso639.CODE_Hiri_Motu:           "Hiri Motu",
	iso639.CODE_Hungarian:           "Hungarian",
	iso639.CODE_Icelandic:           "Icelandic",
	iso639.CODE_Ido:                 "Ido",
	iso639.CODE_Igbo:                "Igbo",
	iso639.CODE_Indonesian:          "Indonesian",
	iso639.CODE_Interlingua:         "Interlingua",
	iso639.CODE_Interlingue:         "Interlingue",
	iso639.CODE_Occidental:          "Interlingue",
	iso639.CODE_Inuktitut:           "Inuktitut",
	iso639.CODE_Inupiaq:             "Inupiaq",
	iso639.CODE_Irish:               "Irish",
	iso639.CODE_Italian:             "Italian",
	iso639.CODE_Japanese:            "Japanese",
	iso639.CODE_Javanese:            "Javanese",
	iso639.CODE_Kannada:             "Kannada",
	iso639.CODE_Kanuri:              "Kanuri",
	iso639.CODE_Kashmiri:            "Kashmiri",
	iso639.CODE_Kazakh:              "Kazakh",
	iso639.CODE_Central_Khmer:       "Central Khmer",
	iso639.CODE_Kikuyu:              "Kikuyu",
	iso639.CODE_Gikuyu:              "Gikuyu",
	iso639.CODE_Kinyarwanda:         "Kinyarwanda",
	iso639.CODE_Kirghiz:             "Kirghiz",
	iso639.CODE_Kyrgyz:              "Kirghiz",
	iso639.CODE_Komi:                "Komi",
	iso639.CODE_Kongo:               "Kongo",
	iso639.CODE_Korean:              "Korean",
	iso639.CODE_Kuanyama:            "Kuanyama",
	iso639.CODE_Kwanyama:            "Kuanyama",
	iso639.CODE_Kurdish:             "Kurdish",
	iso639.CODE_Lao:                 "Lao",
	iso639.CODE_Latin:               "Latin",
	iso639.CODE_Latvian:             "Latvian",
	iso639.CODE_Limburgan:           "Limburgan",
	iso639.CODE_Limburger:           "Limburgan",
	iso639.CODE_Limburgish:          "Limburgan",
	iso639.CODE_Lingala:             "Lingala",
	iso639.CODE_Lithuanian:          "Lithuanian",
	iso639.CODE_Luba_Katanga:        "Luba-Katanga",
	iso639.CODE_Luxembourgish:       "Luxembourgish",
	iso639.CODE_Letzeburgesch:       "Luxembourgish",
	iso639.CODE_Macedonian:          "Macedonian",
	iso639.CODE_Malagasy:            "Malagasy",
	iso639.CODE_Malay:               "Malay",
	iso639.CODE_Malayalam:           "Malayalam",
	iso639.CODE_Maltese:             "Maltese",
	iso639.CODE_Manx:                "Manx",
	iso639.CODE_Maori:               "Maori",
	iso639.CODE_Marathi:             "Marathi",
	iso639.CODE_Marshallese:         "Marshallese",
	iso639.CODE_Mongolian:           "Mongolian",
	iso639.CODE_Nauru:               "Nauru",
	iso639.CODE_Navajo:              "Navajo",
	iso639.CODE_Navaho:              "Navaho",
	iso639.CODE_North_Ndebele:       "North Ndebele",
	iso639.CODE_South_Ndebele:       "South Ndebele",
	iso639.CODE_Ndonga:              "Ndonga",
	iso639.CODE_Nepali:              "Nepali",
	iso639.CODE_Norwegian:           "Norwegian",
	iso639.CODE_Norwegian_Bokmal:    "Norwegian Bokmål",
	iso639.CODE_Norwegian_Nynorsk:   "Norwegian Nynorsk",
	iso639.CODE_Sichuan_Yi:          "Sichuan Yi",
	iso639.CODE_Nuosu:               "Nuosu",
	iso639.CODE_Occitan:             "Occitan",
	iso639.CODE_Ojibwa:              "Ojibwa",
	iso639.CODE_Oriya:               "Oriya",
	iso639.CODE_Oromo:               "Oromo",
	iso639.CODE_Ossetian:            "Ossetian",
	iso639.CODE_Ossetic:             "Ossetic",
	iso639.CODE_Pali:                "Pali",
	iso639.CODE_Pashto:              "Pashto",
	iso639.CODE_Pushto:              "Pashto",
	iso639.CODE_Persian:             "Persian",
	iso639.CODE_Polish:              "Polish",
	iso639.CODE_Portuguese:          "Portuguese",
	iso639.CODE_Punjabi:             "Punjabi",
	iso639.CODE_Panjabi:             "Punjabi",
	iso639.CODE_Quechua:             "Quechua",
	iso639.CODE_Romanian:            "Romanian",
	iso639.CODE_Moldavian:           "Romanian",
	iso639.CODE_Moldovan:            "Romanian",
	iso639.CODE_Romansh:             "Romansh",
	iso639.CODE_Rundi:               "Rundi",
	iso639.CODE_Russian:             "Russian",
	iso639.CODE_Northern_Sami:       "Northern Sami",
	iso639.CODE_Samoan:              "Samoan",
	iso639.CODE_Sango:               "Sango",
	iso639.CODE_Sanskrit:            "Sanskrit",
	iso639.CODE_Sardinian:           "Sardinian",
	iso639.CODE_Serbian:             "Serbian",
	iso639.CODE_Shona:               "Shona",
	iso639.CODE_Sindhi:              "Sindhi",
	iso639.CODE_Sinhala:             "Sinhala",
	iso639.CODE_Sinhalese:           "Sinhalese",
	iso639.CODE_Slovak:              "Slovak",
	iso639.CODE_Slovenian:           "Slovenian",
	iso639.CODE_Somali:              "Somali",
	iso639.CODE_Southern_Sotho:      "Southern Sotho",
	iso639.CODE_Spanish:             "Spanish",
	iso639.CODE_Castilian:           "Spanish",
	iso639.CODE_Sundanese:           "Sundanese",
	iso639.CODE_Swahili:             "Swahili",
	iso639.CODE_Swati:               "Swati",
	iso639.CODE_Swedish:             "Swedish",
	iso639.CODE_Tagalog:             "Tagalog",
	iso639.CODE_Tahitian:            "Tahitian",
	iso639.CODE_Tajik:               "Tajik",
	iso639.CODE_Tamil:               "Tamil",
	iso639.CODE_Tatar:               "Tatar",
	iso639.CODE_Telugu:              "Telugu",
	iso639.CODE_Thai:                "Thai",
	iso639.CODE_Tibetan:             "Tibetan",
	iso639.CODE_Tigrinya:            "Tigrinya",
	iso639.CODE_Tonga:               "Tonga",
	iso639.CODE_Tsonga:              "Tsonga",
	iso639.CODE_Tswana:              "Tswana",
	iso639.CODE_Turkish:             "Turkish",
	iso639.CODE_Turkmen:             "Turkmen",
	iso639.CODE_Twi:                 "Twi",
	iso639.CODE_Uighur:              "Uighur",
	iso639.CODE_Uyghur:              "Uighur",
	iso639.CODE_Ukrainian:           "Ukrainian",
	iso639.CODE_Urdu:                "Urdu",
	iso639.CODE_Uzbek:               "Uzbek",
	iso639.CODE_Venda:               "Venda",
	iso639.CODE_Vietnamese:          "Vietnamese",
	iso639.CODE_Volapuk:             "Volapük",
	iso639.CODE_Walloon:             "Walloon",
	iso639.CODE_Welsh:               "Welsh",
	iso639.CODE_Wolof:               "Wolof",
	iso639.CODE_Xhosa:               "Xhosa",
	iso639.CODE_Yiddish:             "Yiddish",
	iso639.CODE_Yoruba:              "Yoruba",
	iso639.CODE_Zhuang:              "Zhuang",
	iso639.CODE_Chuang:              "Zhuang",
	iso639.CODE_Zulu:                "Zulu",
}

var ids = map[Name]iso639.ID{
	"":                   iso639.CODE_None,
	"Abkhazian":          iso639.CODE_Abkhazian,
	"Afar":               iso639.CODE_Afar,
	"Afrikaans":          iso639.CODE_Afrikaans,
	"Akan":               iso639.CODE_Akan,
	"Albanian":           iso639.CODE_Albanian,
	"Amharic":            iso639.CODE_Amharic,
	"Arabic":             iso639.CODE_Arabic,
	"Aragonese":          iso639.CODE_Aragonese,
	"Armenian":           iso639.CODE_Armenian,
	"Assamese":           iso639.CODE_Assamese,
	"Avaric":             iso639.CODE_Avaric,
	"Avestan":            iso639.CODE_Avestan,
	"Aymara":             iso639.CODE_Aymara,
	"Azerbaijani":        iso639.CODE_Azerbaijani,
	"Bambara":            iso639.CODE_Bambara,
	"Bashkir":            iso639.CODE_Bashkir,
	"Basque":             iso639.CODE_Basque,
	"Belarusian":         iso639.CODE_Belarusian,
	"Bengali":            iso639.CODE_Bengali,
	"Bislama":            iso639.CODE_Bislama,
	"Bosnian":            iso639.CODE_Bosnian,
	"Breton":             iso639.CODE_Breton,
	"Bulgarian":          iso639.CODE_Bulgarian,
	"Burmese":            iso639.CODE_Burmese,
	"Catalan":            iso639.CODE_Catalan,
	"Chamorro":           iso639.CODE_Chamorro,
	"Chechen":            iso639.CODE_Chechen,
	"Chichewa":           iso639.CODE_Chichewa,
	"Chinese":            iso639.CODE_Chinese,
	"Church Slavonic":    iso639.CODE_Church_Slavonic,
	"Chuvash":            iso639.CODE_Chuvash,
	"Cornish":            iso639.CODE_Cornish,
	"Corsican":           iso639.CODE_Corsican,
	"Cree":               iso639.CODE_Cree,
	"Croatian":           iso639.CODE_Croatian,
	"Czech":              iso639.CODE_Czech,
	"Danish":             iso639.CODE_Danish,
	"Maldivian":          iso639.CODE_Maldivian,
	"Dutch":              iso639.CODE_Dutch,
	"Flemish":            iso639.CODE_Flemish,
	"Dzongkha":           iso639.CODE_Dzongkha,
	"English":            iso639.CODE_English,
	"Esperanto":          iso639.CODE_Esperanto,
	"Estonian":           iso639.CODE_Estonian,
	"Ewe":                iso639.CODE_Ewe,
	"Faroese":            iso639.CODE_Faroese,
	"Fijian":             iso639.CODE_Fijian,
	"Finnish":            iso639.CODE_Finnish,
	"French":             iso639.CODE_French,
	"Western Frisian":    iso639.CODE_Western_Frisian,
	"Fulah":              iso639.CODE_Fulah,
	"Gaelic":             iso639.CODE_Gaelic,
	"Galician":           iso639.CODE_Galician,
	"Ganda":              iso639.CODE_Ganda,
	"Georgian":           iso639.CODE_Georgian,
	"German":             iso639.CODE_German,
	"Greek":              iso639.CODE_Greek,
	"Kalaallisut":        iso639.CODE_Kalaallisut,
	"Guarani":            iso639.CODE_Guarani,
	"Gujarati":           iso639.CODE_Gujarati,
	"Haitian":            iso639.CODE_Haitian,
	"Hausa":              iso639.CODE_Hausa,
	"Hebrew":             iso639.CODE_Hebrew,
	"Herero":             iso639.CODE_Herero,
	"Hindi":              iso639.CODE_Hindi,
	"Hiri Motu":          iso639.CODE_Hiri_Motu,
	"Hungarian":          iso639.CODE_Hungarian,
	"Icelandic":          iso639.CODE_Icelandic,
	"Igbo":               iso639.CODE_Ido,
	"Indonesian":         iso639.CODE_Indonesian,
	"Interlingua":        iso639.CODE_Interlingua,
	"Interlingue":        iso639.CODE_Interlingue,
	"Inuktitut":          iso639.CODE_Inuktitut,
	"Inupiaq":            iso639.CODE_Inupiaq,
	"Irish":              iso639.CODE_Irish,
	"Italian":            iso639.CODE_Italian,
	"Japanese":           iso639.CODE_Japanese,
	"Javanese":           iso639.CODE_Javanese,
	"Kannada":            iso639.CODE_Kannada,
	"Kanuri":             iso639.CODE_Kanuri,
	"Kashmiri":           iso639.CODE_Kashmiri,
	"Kazakh":             iso639.CODE_Kazakh,
	"CODE_Central_Khmer": iso639.CODE_Central_Khmer,
	"Kikuyu":             iso639.CODE_Kikuyu,
	"Gikuyu":             iso639.CODE_Gikuyu,
	"Kinyarwanda":        iso639.CODE_Kinyarwanda,
	"Kirghiz":            iso639.CODE_Kirghiz,
	"Komi":               iso639.CODE_Komi,
	"Kongo":              iso639.CODE_Kongo,
	"Korean":             iso639.CODE_Korean,
	"Kuanyama":           iso639.CODE_Kuanyama,
	"Kurdish":            iso639.CODE_Kurdish,
	"Lao":                iso639.CODE_Lao,
	"Latin":              iso639.CODE_Latin,
	"Latvian":            iso639.CODE_Latvian,
	"Limburgan":          iso639.CODE_Limburgan,
	"Lingala":            iso639.CODE_Lingala,
	"Lithuanian":         iso639.CODE_Lithuanian,
	"Luba-Katanga":       iso639.CODE_Luba_Katanga,
	"Luxembourgish":      iso639.CODE_Luxembourgish,
	"Macedonian":         iso639.CODE_Macedonian,
	"Malagasy":           iso639.CODE_Malagasy,
	"Malay":              iso639.CODE_Malay,
	"Malayalam":          iso639.CODE_Malayalam,
	"Maltese":            iso639.CODE_Maltese,
	"Manx":               iso639.CODE_Manx,
	"Maori":              iso639.CODE_Maori,
	"Marathi":            iso639.CODE_Marathi,
	"Marshallese":        iso639.CODE_Marshallese,
	"Mongolian":          iso639.CODE_Mongolian,
	"Nauru":              iso639.CODE_Nauru,
	"Navajo":             iso639.CODE_Navajo,
	"Navaho":             iso639.CODE_Navaho,
	"North Ndebele":      iso639.CODE_North_Ndebele,
	"South Ndebele":      iso639.CODE_South_Ndebele,
	"Ndonga":             iso639.CODE_Ndonga,
	"Nepali":             iso639.CODE_Nepali,
	"Norwegian":          iso639.CODE_Norwegian,
	"Sichuan Yi":         iso639.CODE_Sichuan_Yi,
	"Nuosu":              iso639.CODE_Nuosu,
	"Occitan":            iso639.CODE_Occitan,
	"Ojibwa":             iso639.CODE_Ojibwa,
	"Oriya":              iso639.CODE_Oriya,
	"Oromo":              iso639.CODE_Oromo,
	"Ossetian":           iso639.CODE_Ossetian,
	"Ossetic":            iso639.CODE_Ossetic,
	"Pali":               iso639.CODE_Pali,
	"Pashto":             iso639.CODE_Pashto,
	"Persian":            iso639.CODE_Persian,
	"Polish":             iso639.CODE_Polish,
	"Portuguese":         iso639.CODE_Portuguese,
	"Punjabi":            iso639.CODE_Punjabi,
	"Quechua":            iso639.CODE_Quechua,
	"Romanian":           iso639.CODE_Romanian,
	"Romansh":            iso639.CODE_Romansh,
	"Rundi":              iso639.CODE_Rundi,
	"Russian":            iso639.CODE_Russian,
	"Northern Sami":      iso639.CODE_Northern_Sami,
	"Samoan":             iso639.CODE_Samoan,
	"Sango":              iso639.CODE_Sango,
	"Sanskrit":           iso639.CODE_Sanskrit,
	"Sardinian":          iso639.CODE_Sardinian,
	"Serbian":            iso639.CODE_Serbian,
	"Shona":              iso639.CODE_Shona,
	"Sindhi":             iso639.CODE_Sindhi,
	"Sinhala":            iso639.CODE_Sinhala,
	"Sinhalese":          iso639.CODE_Sinhalese,
	"Slovak":             iso639.CODE_Slovak,
	"Slovenian":          iso639.CODE_Slovenian,
	"Somali":             iso639.CODE_Somali,
	"Southern Sotho":     iso639.CODE_Southern_Sotho,
	"Spanish":            iso639.CODE_Spanish,
	"Sundanese":          iso639.CODE_Sundanese,
	"Swahili":            iso639.CODE_Swahili,
	"Swati":              iso639.CODE_Swati,
	"Swedish":            iso639.CODE_Swedish,
	"Tagalog":            iso639.CODE_Tagalog,
	"Tahitian":           iso639.CODE_Tahitian,
	"Tajik":              iso639.CODE_Tajik,
	"Tamil":              iso639.CODE_Tamil,
	"Tatar":              iso639.CODE_Tatar,
	"Telugu":             iso639.CODE_Telugu,
	"Thai":               iso639.CODE_Thai,
	"Tibetan":            iso639.CODE_Tibetan,
	"Tigrinya":           iso639.CODE_Tigrinya,
	"Tonga":              iso639.CODE_Tonga,
	"Tsonga":             iso639.CODE_Tsonga,
	"Tswana":             iso639.CODE_Tswana,
	"Turkish":            iso639.CODE_Turkish,
	"Turkmen":            iso639.CODE_Turkmen,
	"Twi":                iso639.CODE_Twi,
	"Uighur":             iso639.CODE_Uighur,
	"Ukrainian":          iso639.CODE_Ukrainian,
	"Urdu":               iso639.CODE_Urdu,
	"Uzbek":              iso639.CODE_Uzbek,
	"Venda":              iso639.CODE_Venda,
	"Vietnamese":         iso639.CODE_Vietnamese,
	"Volapük":            iso639.CODE_Volapuk,
	"Walloon":            iso639.CODE_Walloon,
	"Welsh":              iso639.CODE_Welsh,
	"Wolof":              iso639.CODE_Wolof,
	"Xhosa":              iso639.CODE_Xhosa,
	"Yiddish":            iso639.CODE_Yiddish,
	"Yoruba":             iso639.CODE_Yoruba,
	"Zhuang":             iso639.CODE_Zhuang,
	"Zulu":               iso639.CODE_Zulu,
}

func GetID(name string) iso639.ID {

	val, ok := ids[Name(strings.ToLower(name))]
	if !ok {
		return ids[""]
	}
	return val
}

func GetName(id iso639.ID) Name {

	return names[id]
}
