package info

import (
	"github.com/joaoribeirodasilva/countries_info/iso3162"
	"github.com/joaoribeirodasilva/countries_info/iso4217"
)

type Currency struct {
	Code          string
	Num           string
	FullName      string
	Name          string
	Countries     []iso3162.ID
	Symbol        string
	FractUnitName string
	FractDigits   uint
}

var currencies = map[iso4217.ID]Currency{
	iso4217.ID_XXX: {
		Code:          "XXX",
		Num:           "999",
		FullName:      "No currency",
		Name:          "",
		Countries:     []iso3162.ID{},
		Symbol:        "",
		FractUnitName: "",
		FractDigits:   0,
	},
	iso4217.ID_AED: {
		Code:     "AED",
		Num:      "784",
		FullName: "United Arab Emirates Dirham",
		Name:     "Dirham",
		Countries: []iso3162.ID{
			iso3162.ID_United_Arab_Emirates,
		},
		Symbol:        "Dh",
		FractUnitName: "Fils",
		FractDigits:   2,
	},
	iso4217.ID_AFN: {
		Code:     "AFN",
		Num:      "971",
		FullName: "Afghan Afghani",
		Name:     "Afghani",
		Countries: []iso3162.ID{
			iso3162.ID_Afghanistan,
		},
		Symbol:        "؋",
		FractUnitName: "Pul",
		FractDigits:   2,
	},
	iso4217.ID_ALL: {
		Code:     "ALL",
		Num:      "008",
		FullName: "Albanian Lek",
		Name:     "Lek",
		Countries: []iso3162.ID{
			iso3162.ID_Albania,
		},
		Symbol:        "Lek",
		FractUnitName: "Qintar",
		FractDigits:   2,
	},
	iso4217.ID_AMD: {
		Code:     "ALL",
		Num:      "051",
		FullName: "Armenian Dram",
		Name:     "Dram",
		Countries: []iso3162.ID{
			iso3162.ID_Armenia,
		},
		Symbol:        "֏",
		FractUnitName: "Luma",
		FractDigits:   2,
	},
	iso4217.ID_ANG: {
		Code:     "ANG",
		Num:      "532",
		FullName: "Netherlands Antillean Guilder",
		Name:     "Guilder",
		Countries: []iso3162.ID{
			iso3162.ID_Curacao,
			iso3162.ID_Sint_Maarten_Dutch,
		},
		Symbol:        "ƒ",
		FractUnitName: "Cent",
		FractDigits:   2,
	},
	iso4217.ID_AOA: {
		Code:          "AOA",
		Num:           "973",
		FullName:      "Angolan Kwanza",
		Name:          "Kwanza",
		Countries:     []iso3162.ID{iso3162.ID_Angola},
		Symbol:        "Kz",
		FractUnitName: "Cêntimo",
		FractDigits:   2,
	},
	iso4217.ID_ARS: {
		Code:     "ARS",
		Num:      "032",
		FullName: "Argentine Peso",
		Name:     "Peso",
		Countries: []iso3162.ID{
			iso3162.ID_Argentina,
		},
		Symbol:        "$",
		FractUnitName: "Centavo",
		FractDigits:   2,
	},
	iso4217.ID_AUD: {
		Code:     "AUD",
		Num:      "036",
		FullName: "Australian Dollar",
		Name:     "Dollar",
		Countries: []iso3162.ID{
			iso3162.ID_Australia,
			iso3162.ID_Christmas_Island,
			iso3162.ID_Cocos_Islands,
			iso3162.ID_Heard_Island_And_McDonald_Islands,
			iso3162.ID_Kiribati,
			iso3162.ID_Norfolk_Island,
			iso3162.ID_Tuvalu,
		},
		Symbol:        "$",
		FractUnitName: "Centavo",
		FractDigits:   2,
	},
	iso4217.ID_AWG: {
		Code:     "AWG",
		Num:      "533",
		FullName: "Aruban Florin",
		Name:     "Florin",
		Countries: []iso3162.ID{
			iso3162.ID_Aruba,
		},
		Symbol:        "$",
		FractUnitName: "Centavo",
		FractDigits:   2,
	},
	iso4217.ID_AZN: {
		Code:     "AZN",
		Num:      "944",
		FullName: "Azerbaijani Manat",
		Name:     "Manat",
		Countries: []iso3162.ID{
			iso3162.ID_Azerbaijan,
		},
		Symbol:        "₼",
		FractUnitName: "Qəpik",
		FractDigits:   2,
	},
	iso4217.ID_BAM: {
		Code:     "BAM",
		Num:      "977",
		FullName: "Bosnia and Herzegovina Mark",
		Name:     "Mark",
		Countries: []iso3162.ID{
			iso3162.ID_Bosnia_And_Herzegovina,
		},
		Symbol:        "KM",
		FractUnitName: "Fening",
		FractDigits:   2,
	},
	iso4217.ID_BBD: {
		Code:     "BBD",
		Num:      "052",
		FullName: "Barbados Dollar",
		Name:     "Dollar",
		Countries: []iso3162.ID{
			iso3162.ID_Barbados,
		},
		Symbol:        "$",
		FractUnitName: "Cent",
		FractDigits:   2,
	},
	iso4217.ID_BDT: {
		Code:     "BDT",
		Num:      "050",
		FullName: "Bangladeshi Taka",
		Name:     "Taka",
		Countries: []iso3162.ID{
			iso3162.ID_Bangladesh,
		},
		Symbol:        "৳",
		FractUnitName: "Poisha",
		FractDigits:   2,
	},
	iso4217.ID_BGN: {
		Code:     "BGN",
		Num:      "975",
		FullName: "Bulgarian Lev",
		Name:     "Lev",
		Countries: []iso3162.ID{
			iso3162.ID_Bulgaria,
		},
		Symbol:        "Lev",
		FractUnitName: "Stotinka",
		FractDigits:   2,
	},
	iso4217.ID_BHD: {
		Code:     "BHD",
		Num:      "048",
		FullName: "Bahraini Dinar",
		Name:     "Dinar",
		Countries: []iso3162.ID{
			iso3162.ID_Bahrain,
		},
		Symbol:        "BD",
		FractUnitName: "Fils",
		FractDigits:   3,
	},
	iso4217.ID_BIF: {
		Code:     "BIF",
		Num:      "108",
		FullName: "Burundian Franc",
		Name:     "Franc",
		Countries: []iso3162.ID{
			iso3162.ID_Burundi,
		},
		Symbol:        "Fr",
		FractUnitName: "Centime",
		FractDigits:   0,
	},
	iso4217.ID_BMD: {
		Code:     "BMD",
		Num:      "060",
		FullName: "Bermudian Dollar",
		Name:     "Dollar",
		Countries: []iso3162.ID{
			iso3162.ID_Bermuda,
		},
		Symbol:        "$",
		FractUnitName: "Cent",
		FractDigits:   2,
	},
	iso4217.ID_BND: {
		Code:     "BND",
		Num:      "096",
		FullName: "Brunei Dollar",
		Name:     "Dollar",
		Countries: []iso3162.ID{
			iso3162.ID_Brunei_Darussalam,
		},
		Symbol:        "$",
		FractUnitName: "Sen",
		FractDigits:   2,
	},
	iso4217.ID_BOB: {
		Code:     "BOB",
		Num:      "068",
		FullName: "Boliviano",
		Name:     "Boliviano",
		Countries: []iso3162.ID{
			iso3162.ID_Bolivia,
		},
		Symbol:        "Bs",
		FractUnitName: "Centavo",
		FractDigits:   2,
	},
	iso4217.ID_BRL: {
		Code:     "BRL",
		Num:      "986",
		FullName: "Brazilian Real",
		Name:     "Real",
		Countries: []iso3162.ID{
			iso3162.ID_Brazil,
		},
		Symbol:        "R$",
		FractUnitName: "Centavo",
		FractDigits:   2,
	},
	iso4217.ID_BSD: {
		Code:     "BSD",
		Num:      "044",
		FullName: "Bahamian Dollar",
		Name:     "Dollar",
		Countries: []iso3162.ID{
			iso3162.ID_Bahamas,
		},
		Symbol:        "$",
		FractUnitName: "Cent",
		FractDigits:   2,
	},
	iso4217.ID_BTN: {
		Code:     "BTN",
		Num:      "064",
		FullName: "Bhutanese Ngultrum",
		Name:     "Ngultrum",
		Countries: []iso3162.ID{
			iso3162.ID_Bhutan,
		},
		Symbol:        "Nu",
		FractUnitName: "Chetrum",
		FractDigits:   2,
	},
	iso4217.ID_BWP: {
		Code:     "BWP",
		Num:      "072",
		FullName: "Botswana Pula",
		Name:     "Pula",
		Countries: []iso3162.ID{
			iso3162.ID_Botswana,
		},
		Symbol:        "P",
		FractUnitName: "Thebe",
		FractDigits:   2,
	},
	iso4217.ID_BYN: {
		Code:     "BYN",
		Num:      "933",
		FullName: "Belarusian Ruble",
		Name:     "Ruble",
		Countries: []iso3162.ID{
			iso3162.ID_Belarus,
		},
		Symbol:        "Br",
		FractUnitName: "Copeck",
		FractDigits:   2,
	},
	iso4217.ID_BZD: {
		Code:     "BZD",
		Num:      "084",
		FullName: "Belize Dollar",
		Name:     "Dollar",
		Countries: []iso3162.ID{
			iso3162.ID_Belize,
		},
		Symbol:        "$",
		FractUnitName: "Cent",
		FractDigits:   2,
	},
	iso4217.ID_CAD: {
		Code:     "CAD",
		Num:      "124",
		FullName: "Canadian Dollar",
		Name:     "Dollar",
		Countries: []iso3162.ID{
			iso3162.ID_Canada,
		},
		Symbol:        "$",
		FractUnitName: "Cent",
		FractDigits:   2,
	},
	iso4217.ID_CDF: {
		Code:     "CDF",
		Num:      "976",
		FullName: "Congolese Franc",
		Name:     "Franc",
		Countries: []iso3162.ID{
			iso3162.ID_Congo_Democratic_Republic_Of,
		},
		Symbol:        "Fr",
		FractUnitName: "Centime",
		FractDigits:   2,
	},
	iso4217.ID_CHF: {
		Code:     "CHF",
		Num:      "756",
		FullName: "Swiss Franc",
		Name:     "Franc",
		Countries: []iso3162.ID{
			iso3162.ID_Switzerland,
			iso3162.ID_Liechtenstein,
		},
		Symbol:        "Fr",
		FractUnitName: "Rappen",
		FractDigits:   2,
	},
	iso4217.ID_CLP: {
		Code:     "CLP",
		Num:      "152",
		FullName: "Chilean Peso",
		Name:     "Peso",
		Countries: []iso3162.ID{
			iso3162.ID_Chile,
		},
		Symbol:        "$",
		FractUnitName: "Centavo",
		FractDigits:   0,
	},
	iso4217.ID_COP: {
		Code:     "COP",
		Num:      "170",
		FullName: "Colombian Peso",
		Name:     "Peso",
		Countries: []iso3162.ID{
			iso3162.ID_Colombia,
		},
		Symbol:        "$",
		FractUnitName: "Centavo",
		FractDigits:   2,
	},
	iso4217.ID_CRC: {
		Code:     "CRC",
		Num:      "188",
		FullName: "Costa Rica Colon",
		Name:     "Colon",
		Countries: []iso3162.ID{
			iso3162.ID_Costa_Rica,
		},
		Symbol:        "₡",
		FractUnitName: "Céntimo",
		FractDigits:   2,
	},
	iso4217.ID_CUP: {
		Code:     "CUP",
		Num:      "192",
		FullName: "Cuban Peso",
		Name:     "Peso",
		Countries: []iso3162.ID{
			iso3162.ID_Cuba,
		},
		Symbol:        "$",
		FractUnitName: "Centavo",
		FractDigits:   2,
	},
	iso4217.ID_CVE: {
		Code:     "CVE",
		Num:      "132",
		FullName: "Cape Verde Escudo",
		Name:     "Escudo",
		Countries: []iso3162.ID{
			iso3162.ID_Cabo_Verde,
		},
		Symbol:        "$",
		FractUnitName: "Centavo",
		FractDigits:   2,
	},
	iso4217.ID_CZK: {
		Code:     "CZK",
		Num:      "203",
		FullName: "Czech Koruna",
		Name:     "Koruna",
		Countries: []iso3162.ID{
			iso3162.ID_Czechia,
		},
		Symbol:        "Kč",
		FractUnitName: "Heller",
		FractDigits:   2,
	},
	iso4217.ID_DJF: {
		Code:     "DJF",
		Num:      "262",
		FullName: "Djiboutian Franc",
		Name:     "Franc",
		Countries: []iso3162.ID{
			iso3162.ID_Djibouti,
		},
		Symbol:        "Fr",
		FractUnitName: "Centime",
		FractDigits:   0,
	},
	iso4217.ID_DKK: {
		Code:     "DKK",
		Num:      "208",
		FullName: "Danish Krone",
		Name:     "Krone",
		Countries: []iso3162.ID{
			iso3162.ID_Denmark,
			iso3162.ID_Faroe_Islands,
			iso3162.ID_Greenland,
		},
		Symbol:        "kr",
		FractUnitName: "Øre",
		FractDigits:   2,
	},
	iso4217.ID_DOP: {
		Code:     "DOP",
		Num:      "214",
		FullName: "Dominican Peso",
		Name:     "Peso",
		Countries: []iso3162.ID{
			iso3162.ID_Dominican_Republic,
		},
		Symbol:        "$",
		FractUnitName: "Centavo",
		FractDigits:   2,
	},
	iso4217.ID_DZD: {
		Code:     "DZD",
		Num:      "012",
		FullName: "Algerian Dinar",
		Name:     "Dinar",
		Countries: []iso3162.ID{
			iso3162.ID_Algeria,
		},
		Symbol:        "DA",
		FractUnitName: "Santeem",
		FractDigits:   2,
	},
	iso4217.ID_EGP: {
		Code:     "EGP",
		Num:      "818",
		FullName: "Egyptian Pound",
		Name:     "Pound",
		Countries: []iso3162.ID{
			iso3162.ID_Egypt,
		},
		Symbol:        "LE",
		FractUnitName: "Piastre",
		FractDigits:   2,
	},
	iso4217.ID_ERN: {
		Code:     "ERN",
		Num:      "232",
		FullName: "Eritrean Nakfa",
		Name:     "Nakfa",
		Countries: []iso3162.ID{
			iso3162.ID_Eritrea,
		},
		Symbol:        "Nkf",
		FractUnitName: "Cent",
		FractDigits:   2,
	},
	iso4217.ID_ETB: {
		Code:     "ETB",
		Num:      "230",
		FullName: "Ethiopian Birr",
		Name:     "Birr",
		Countries: []iso3162.ID{
			iso3162.ID_Ethiopia,
		},
		Symbol:        "Br",
		FractUnitName: "Santim",
		FractDigits:   2,
	},
	iso4217.ID_EUR: {
		Code:     "EUR",
		Num:      "978",
		FullName: "Euro",
		Name:     "Euro",
		Countries: []iso3162.ID{
			iso3162.ID_Aland_Islands,
			iso3162.ID_Andorra,
			iso3162.ID_Austria,
			iso3162.ID_Belgium,
			iso3162.ID_Croatia,
			iso3162.ID_Cyprus,
			iso3162.ID_Estonia,
			iso3162.ID_Finland,
			iso3162.ID_France,
			iso3162.ID_French_Guiana,
			iso3162.ID_French_Southern_Territories,
			iso3162.ID_Germany,
			iso3162.ID_Greece,
			iso3162.ID_Guadeloupe,
			iso3162.ID_Ireland,
			iso3162.ID_Italy,
			iso3162.ID_Latvia,
			iso3162.ID_Lithuania,
			iso3162.ID_Luxembourg,
			iso3162.ID_Malta,
			iso3162.ID_Martinique,
			iso3162.ID_Mayotte,
			iso3162.ID_Monaco,
			iso3162.ID_Montenegro,
			iso3162.ID_Netherlands,
			iso3162.ID_Portugal,
			iso3162.ID_Saint_Barthelemy,
			iso3162.ID_Saint_Martin_French,
			iso3162.ID_Saint_Pierre_And_Miquelon,
			iso3162.ID_San_Marino,
			iso3162.ID_Slovakia,
			iso3162.ID_Slovenia,
			iso3162.ID_Spain,
			iso3162.ID_Vatican,
		},
		Symbol:        "€",
		FractUnitName: "Cent",
		FractDigits:   2,
	},
	iso4217.ID_FJD: {
		Code:     "FJD",
		Num:      "242",
		FullName: "Fiji Dollar",
		Name:     "Dollar",
		Countries: []iso3162.ID{
			iso3162.ID_Fiji,
		},
		Symbol:        "$",
		FractUnitName: "Cent",
		FractDigits:   2,
	},
	iso4217.ID_FKP: {
		Code:     "FKP",
		Num:      "238",
		FullName: "Falkland Islands Pound",
		Name:     "Pound",
		Countries: []iso3162.ID{
			iso3162.ID_Falkland_Islands,
		},
		Symbol:        "£",
		FractUnitName: "Penny",
		FractDigits:   2,
	},
	iso4217.ID_GBP: {
		Code:     "GBP",
		Num:      "826",
		FullName: "Pound Sterling",
		Name:     "Pound",
		Countries: []iso3162.ID{
			iso3162.ID_United_Kingdom,
			iso3162.ID_Isle_Of_Man,
			iso3162.ID_Jersey,
			iso3162.ID_Guernsey,
			iso3162.ID_Saint_Helena_Ascension_And_Tristan_Da_Cunha,
		},
		Symbol:        "£",
		FractUnitName: "Penny",
		FractDigits:   2,
	},
	iso4217.ID_GEL: {
		Code:     "GEL",
		Num:      "981",
		FullName: "Georgian Lari",
		Name:     "Lari",
		Countries: []iso3162.ID{
			iso3162.ID_Georgia,
		},
		Symbol:        "₾",
		FractUnitName: "Tetri",
		FractDigits:   2,
	},
	iso4217.ID_GHS: {
		Code:     "GHS",
		Num:      "936",
		FullName: "Ghanaian Cedi",
		Name:     "Cedi",
		Countries: []iso3162.ID{
			iso3162.ID_Ghana,
		},
		Symbol:        "₵",
		FractUnitName: "Pesewa",
		FractDigits:   2,
	},
	iso4217.ID_GIP: {
		Code:     "GIP",
		Num:      "292",
		FullName: "Gibraltar Pound",
		Name:     "Pound",
		Countries: []iso3162.ID{
			iso3162.ID_Gibraltar,
		},
		Symbol:        "£",
		FractUnitName: "Penny",
		FractDigits:   2,
	},
	iso4217.ID_GMD: {
		Code:     "GMD",
		Num:      "270",
		FullName: "Gambian Dalasi",
		Name:     "Dalasi",
		Countries: []iso3162.ID{
			iso3162.ID_Gambia,
		},
		Symbol:        "D",
		FractUnitName: "Butut",
		FractDigits:   2,
	},
}

// TODO: Atrelar o FractUnitName à língua

func GetByID(id iso4217.ID) Currency {

	val, ok := currencies[id]
	if !ok {
		return currencies[iso4217.ID_XXX]
	}
	return val
}

// func GetByCode(code string) Currency {

// }
