// source: https://en.wikipedia.org/wiki/ISO_3166-2
package names

import (
	"strings"

	"github.com/joaoribeirodasilva/countries_info/iso3162"
)

// Country code
type Name string

var names = map[iso3162.ID]Name{
	iso3162.ID_None:                         "",
	iso3162.ID_Andorra:                      "Andorra",
	iso3162.ID_United_Arab_Emirates:         "United Arab Emirates",
	iso3162.ID_Afghanistan:                  "Afghanistan",
	iso3162.ID_Antigua_And_Barbuda:          "Antigua and Barbuda",
	iso3162.ID_Anguilla:                     "Anguilla",
	iso3162.ID_Albania:                      "Albania",
	iso3162.ID_Armenia:                      "Armenia",
	iso3162.ID_Angola:                       "Angola",
	iso3162.ID_Antarctica:                   "Antarctica",
	iso3162.ID_Argentina:                    "Argentina",
	iso3162.ID_American_Samoa:               "American Samoa",
	iso3162.ID_Austria:                      "Austria",
	iso3162.ID_Australia:                    "Australia",
	iso3162.ID_Aruba:                        "Aruba",
	iso3162.ID_Aland_Islands:                "Aland Islands",
	iso3162.ID_Azerbaijan:                   "Azerbaijan",
	iso3162.ID_Bosnia_And_Herzegovina:       "Bosnia and Herzegovina",
	iso3162.ID_Barbados:                     "Barbados",
	iso3162.ID_Bangladesh:                   "Bangladesh",
	iso3162.ID_Belgium:                      "Belgium",
	iso3162.ID_Burkina_Faso:                 "Burkina Faso",
	iso3162.ID_Bulgaria:                     "Bulgaria",
	iso3162.ID_Bahrain:                      "Bahrain",
	iso3162.ID_Burundi:                      "Burundi",
	iso3162.ID_Benin:                        "Benin",
	iso3162.ID_Saint_Barthelemy:             "Saint Barthelemy",
	iso3162.ID_Bermuda:                      "Bermuda",
	iso3162.ID_Brunei_Darussalam:            "Brunei Darussalam",
	iso3162.ID_Bolivia:                      "Bolivia",
	iso3162.ID_Bonaire:                      "Bonaire",
	iso3162.ID_Brazil:                       "Brazil",
	iso3162.ID_Bahamas:                      "Bahamas",
	iso3162.ID_Bhutan:                       "Bhutan",
	iso3162.ID_Bouvet_Island:                "Bouvet Island",
	iso3162.ID_Botswana:                     "Botswana",
	iso3162.ID_Belarus:                      "Belarus",
	iso3162.ID_Belize:                       "Belize",
	iso3162.ID_Canada:                       "Canada",
	iso3162.ID_Cocos_Islands:                "Cocos Islands",
	iso3162.ID_Congo_Democratic_Republic_Of: "Congo, Democratic Republic of",
	iso3162.ID_Central_African_Republic:     "Central African Republic",
	iso3162.ID_Congo:                        "Congo",
	iso3162.ID_Switzerland:                  "Switzerland",
	iso3162.ID_Cote_d_Ivoire:                "Cote d'Ivoire",
	iso3162.ID_Cook_Islands:                 "Cook Islands",
	iso3162.ID_Chile:                        "Chile",
	iso3162.ID_Cameroon:                     "Cameroon",
	iso3162.ID_China:                        "China",
	iso3162.ID_Colombia:                     "Colombia",
	iso3162.ID_Costa_Rica:                   "Costa Rica",
	iso3162.ID_Cuba:                         "Cuba",
	iso3162.ID_Cabo_Verde:                   "Cabo Verde",
	iso3162.ID_Curacao:                      "Curacao",
	iso3162.ID_Christmas_Island:             "Christmas Island",
	iso3162.ID_Cyprus:                       "Cyprus",
	iso3162.ID_Czechia:                      "Czechia",
	iso3162.ID_Germany:                      "Germany",
	iso3162.ID_Djibouti:                     "Djibouti",
	iso3162.ID_Denmark:                      "Denmark",
	iso3162.ID_Dominica:                     "Dominica",
	iso3162.ID_Dominican_Republic:           "Dominican Republic",
	iso3162.ID_Algeria:                      "Algeria",
	iso3162.ID_Ecuador:                      "Ecuador",
	iso3162.ID_Estonia:                      "Estonia",
	iso3162.ID_Egypt:                        "Egypt",
	iso3162.ID_Western_Sahara:               "Western Sahara",
	iso3162.ID_Eritrea:                      "Eritrea",
	iso3162.ID_Spain:                        "Spain",
	iso3162.ID_Ethiopia:                     "Ethiopia",
	iso3162.ID_Finland:                      "Finland",
	iso3162.ID_Fiji:                         "Fiji",
	iso3162.ID_Falkland_Islands:             "Falkland Islands",
	iso3162.ID_Micronesia:                   "Micronesia",
	iso3162.ID_Faroe_Islands:                "Faroe Islands",
	iso3162.ID_France:                       "France",
	iso3162.ID_Gabon:                        "Gabon",
	iso3162.ID_United_Kingdom:               "United Kingdom",
	iso3162.ID_Grenada:                      "Grenada",
	iso3162.ID_Georgia:                      "Georgia",
	iso3162.ID_French_Guiana:                "French Guiana",
	iso3162.ID_Guernsey:                     "Guernsey",
	iso3162.ID_Ghana:                        "Ghana",
	iso3162.ID_Gibraltar:                    "Gibraltar",
	iso3162.ID_Greenland:                    "Greenland",
	iso3162.ID_Gambia:                       "Gambia",
	iso3162.ID_Guinea:                       "Guinea",
	iso3162.ID_Guadeloupe:                   "Guadeloupe",
	iso3162.ID_Equatorial_Guinea:            "Equatorial Guinea",
	iso3162.ID_Greece:                       "Greece",
	iso3162.ID_South_Georgia_And_South_Sandwich_Islands: "South Georgia and South Sandwich Islands",
	iso3162.ID_Guatemala:                         "Guatemala",
	iso3162.ID_Guam:                              "Guam",
	iso3162.ID_Guinea_Bissau:                     "Guinea Bissau",
	iso3162.ID_Guyana:                            "Guyana",
	iso3162.ID_Hong_Kong:                         "Hong Kong",
	iso3162.ID_Heard_Island_And_McDonald_Islands: "Heard Island and McDonald Islands",
	iso3162.ID_Honduras:                          "Honduras",
	iso3162.ID_Croatia:                           "Croatia",
	iso3162.ID_Haiti:                             "Haiti",
	iso3162.ID_Hungary:                           "Hungary",
	iso3162.ID_Indonesia:                         "Indonesia",
	iso3162.ID_Ireland:                           "Ireland",
	iso3162.ID_Israel:                            "Israel",
	iso3162.ID_Isle_Of_Man:                       "Isle of Man",
	iso3162.ID_India:                             "India",
	iso3162.ID_British_Indian_Ocean_Territory:    "British Indian Ocean Territory",
	iso3162.ID_Iraq:                              "Iraq",
	iso3162.ID_Iran:                              "Iran",
	iso3162.ID_Iceland:                           "Iceland",
	iso3162.ID_Italy:                             "Italy",
	iso3162.ID_Jersey:                            "Jersey",
	iso3162.ID_Jamaica:                           "Jamaica",
	iso3162.ID_Jordan:                            "Jordan",
	iso3162.ID_Japan:                             "Japan",
	iso3162.ID_Kenya:                             "Kenya",
	iso3162.ID_Kyrgyzstan:                        "Kyrgyzstan",
	iso3162.ID_Cambodia:                          "Cambodia",
	iso3162.ID_Kiribati:                          "Kiribati",
	iso3162.ID_Comoros:                           "Comoros",
	iso3162.ID_Saint_Kitts_And_Nevis:             "Saint Kitts and Nevis",
	iso3162.ID_North_Korea:                       "North Korea",
	iso3162.ID_South_Korea:                       "South Korea",
	iso3162.ID_Kuwait:                            "Kuwait",
	iso3162.ID_Cayman_Islands:                    "Cayman Islands",
	iso3162.ID_Kazakhstan:                        "Kazakhstan",
	iso3162.ID_Lao:                               "Lao",
	iso3162.ID_Lebanon:                           "Lebanon",
	iso3162.ID_Saint_Lucia:                       "Saint Lucia",
	iso3162.ID_Liechtenstein:                     "Liechtenstein",
	iso3162.ID_Sri_Lanka:                         "Sri Lanka",
	iso3162.ID_Liberia:                           "Liberia",
	iso3162.ID_Lesotho:                           "Lesotho",
	iso3162.ID_Lithuania:                         "Lithuania",
	iso3162.ID_Luxembourg:                        "Luxembourg",
	iso3162.ID_Latvia:                            "Latvia",
	iso3162.ID_Libya:                             "Libya",
	iso3162.ID_Morocco:                           "Morocco",
	iso3162.ID_Monaco:                            "Monaco",
	iso3162.ID_Moldova:                           "Moldova",
	iso3162.ID_Montenegro:                        "Montenegro",
	iso3162.ID_Saint_Martin_French:               "Saint Martin (French)",
	iso3162.ID_Madagascar:                        "Madagascar",
	iso3162.ID_Marshall_Islands:                  "Marshall Islands",
	iso3162.ID_North_Macedonia:                   "North Macedonia",
	iso3162.ID_Mali:                              "Mali",
	iso3162.ID_Myanmar:                           "Myanmar",
	iso3162.ID_Mongolia:                          "Mongolia",
	iso3162.ID_Macao:                             "Macao",
	iso3162.ID_Northern_Mariana_Islands:          "Northern Mariana Islands",
	iso3162.ID_Martinique:                        "Martinique",
	iso3162.ID_Mauritania:                        "Mauritania",
	iso3162.ID_Montserrat:                        "Montserrat",
	iso3162.ID_Malta:                             "Malta",
	iso3162.ID_Mauritius:                         "Mauritius",
	iso3162.ID_Maldives:                          "Maldives",
	iso3162.ID_Malawi:                            "Malawi",
	iso3162.ID_Mexico:                            "Mexico",
	iso3162.ID_Malaysia:                          "Malaysia",
	iso3162.ID_Mozambique:                        "Mozambique",
	iso3162.ID_Namibia:                           "Namibia",
	iso3162.ID_New_Caledonia:                     "New_Caledonia",
	iso3162.ID_Niger:                             "Niger",
	iso3162.ID_Norfolk_Island:                    "Norfolk_Island",
	iso3162.ID_Nigeria:                           "Nigeria",
	iso3162.ID_Nicaragua:                         "Nicaragua",
	iso3162.ID_Netherlands:                       "Netherlands",
	iso3162.ID_Norway:                            "Norway",
	iso3162.ID_Nepal:                             "Nepal",
	iso3162.ID_Nauru:                             "Nauru",
	iso3162.ID_Niue:                              "Niue",
	iso3162.ID_New_Zealand:                       "New Zealand",
	iso3162.ID_Oman:                              "Oman",
	iso3162.ID_Panama:                            "Panama",
	iso3162.ID_Peru:                              "Peru",
	iso3162.ID_French_Polynesia:                  "French Polynesia",
	iso3162.ID_Papua_New_Guinea:                  "Papua New Guinea",
	iso3162.ID_Philippines:                       "Philippines",
	iso3162.ID_Pakistan:                          "Pakistan",
	iso3162.ID_Poland:                            "Poland",
	iso3162.ID_Saint_Pierre_And_Miquelon:         "Saint Pierre and Miquelon",
	iso3162.ID_Pitcairn:                          "Pitcairn",
	iso3162.ID_Puerto_Rico:                       "Puerto Rico",
	iso3162.ID_Palestine:                         "Palestine",
	iso3162.ID_Portugal:                          "Portugal",
	iso3162.ID_Palau:                             "Palau",
	iso3162.ID_Paraguay:                          "Paraguay",
	iso3162.ID_Qatar:                             "Qatar",
	iso3162.ID_Russia:                            "Russia",
	iso3162.ID_Rwanda:                            "Rwanda",
	iso3162.ID_Saudi_Arabia:                      "Saudi Arabia",
	iso3162.ID_Solomon_Islands:                   "Solomon Islands",
	iso3162.ID_Seychelles:                        "Seychelles",
	iso3162.ID_Sudan:                             "Sudan",
	iso3162.ID_Sweden:                            "Sweden",
	iso3162.ID_Singapore:                         "Singapore",
	iso3162.ID_Saint_Helena_Ascension_And_Tristan_Da_Cunha: "Saint Helena, Ascension and Tristan da Cunha",
	iso3162.ID_Slovenia:                             "Slovenia",
	iso3162.ID_Svalbard_And_Jan_Mayen:               "Svalbard and Jan Mayen",
	iso3162.ID_Slovakia:                             "Slovakia",
	iso3162.ID_Sierra_Leone:                         "Sierra Leone",
	iso3162.ID_San_Marino:                           "San Marino",
	iso3162.ID_Senegal:                              "Senegal",
	iso3162.ID_Somalia:                              "Somalia",
	iso3162.ID_Suriname:                             "Suriname",
	iso3162.ID_South_Sudan:                          "South Sudan",
	iso3162.ID_Sao_Tome_And_Principe:                "Sao Tome and Principe",
	iso3162.ID_El_Salvador:                          "El Salvador",
	iso3162.ID_Sint_Maarten_Dutch:                   "Sint Maarten (Dutch)",
	iso3162.ID_Syria:                                "Syria",
	iso3162.ID_Eswatini:                             "Eswatini",
	iso3162.ID_Turks_And_Caicos_Islands:             "Turks and Caicos Islands",
	iso3162.ID_Chad:                                 "Chad",
	iso3162.ID_French_Southern_Territories:          "French Southern Territories",
	iso3162.ID_Togo:                                 "Togo",
	iso3162.ID_Thailand:                             "Thailand",
	iso3162.ID_Tajikistan:                           "Tajikistan",
	iso3162.ID_Tokelau:                              "Tokelau",
	iso3162.ID_Timor_Leste:                          "Timor Leste",
	iso3162.ID_Turkmenistan:                         "Turkmenistan",
	iso3162.ID_Tunisia:                              "Tunisia",
	iso3162.ID_Tonga:                                "Tonga",
	iso3162.ID_Turkey:                               "Turkey",
	iso3162.ID_Trinidad_And_Tobago:                  "Trinidad and Tobago",
	iso3162.ID_Tuvalu:                               "Tuvalu",
	iso3162.ID_Taiwan:                               "Taiwan",
	iso3162.ID_Tanzania:                             "Tanzania",
	iso3162.ID_Ukraine:                              "Ukraine",
	iso3162.ID_United_States_Minor_Outlying_Islands: "United States Minor Outlying Islands",
	iso3162.ID_United_States:                        "United States",
	iso3162.ID_Uruguay:                              "Uruguay",
	iso3162.ID_Uzbekistan:                           "Uzbekistan",
	iso3162.ID_Holy_See:                             "Holy See",
	iso3162.ID_Vatican:                              "Vatican",
	iso3162.ID_Saint_Vincent_And_The_Grenadines:     "Saint Vincent and The Grenadines",
	iso3162.ID_Venezuela:                            "Venezuela",
	iso3162.ID_Virgin_Islands_British:               "Virgin Islands (British)",
	iso3162.ID_Virgin_Islands_US:                    "Virgin Islands (US)",
	iso3162.ID_Vietnam:                              "Vietnam",
	iso3162.ID_Vanuatu:                              "Vanuatu",
	iso3162.ID_Wallis_And_Futuna:                    "Wallis and Futuna",
	iso3162.ID_Samoa:                                "Samoa",
	iso3162.ID_Yemen:                                "Yemen",
	iso3162.ID_Mayotte:                              "Mayotte",
	iso3162.ID_South_Africa:                         "South Africa",
	iso3162.ID_Zambia:                               "Zambia",
	iso3162.ID_Zimbabwe:                             "Zimbabwe",
}

var ids = map[Name]iso3162.ID{
	"":                              iso3162.ID_None,
	"Andorra":                       iso3162.ID_Andorra,
	"United Arab Emirates":          iso3162.ID_United_Arab_Emirates,
	"Afghanistan":                   iso3162.ID_Afghanistan,
	"Antigua and Barbuda":           iso3162.ID_Antigua_And_Barbuda,
	"Anguilla":                      iso3162.ID_Anguilla,
	"Albania":                       iso3162.ID_Albania,
	"Armenia":                       iso3162.ID_Armenia,
	"Angola":                        iso3162.ID_Angola,
	"Antarctica":                    iso3162.ID_Antarctica,
	"Argentina":                     iso3162.ID_Argentina,
	"American Samoa":                iso3162.ID_American_Samoa,
	"Austria":                       iso3162.ID_Austria,
	"Australia":                     iso3162.ID_Australia,
	"Aruba":                         iso3162.ID_Aruba,
	"Aland Islands":                 iso3162.ID_Aland_Islands,
	"Azerbaijan":                    iso3162.ID_Azerbaijan,
	"Bosnia and Herzegovina":        iso3162.ID_Bosnia_And_Herzegovina,
	"Barbados":                      iso3162.ID_Barbados,
	"Bangladesh":                    iso3162.ID_Bangladesh,
	"Belgium":                       iso3162.ID_Belgium,
	"Burkina Faso":                  iso3162.ID_Burkina_Faso,
	"Bulgaria":                      iso3162.ID_Bulgaria,
	"Bahrain":                       iso3162.ID_Bahrain,
	"Burundi":                       iso3162.ID_Burundi,
	"Benin":                         iso3162.ID_Benin,
	"Saint Barthelemy":              iso3162.ID_Saint_Barthelemy,
	"Bermuda":                       iso3162.ID_Bermuda,
	"Brunei Darussalam":             iso3162.ID_Brunei_Darussalam,
	"Bolivia":                       iso3162.ID_Bolivia,
	"Bonaire":                       iso3162.ID_Bonaire,
	"Brazil":                        iso3162.ID_Brazil,
	"Bahamas":                       iso3162.ID_Bahamas,
	"Bhutan":                        iso3162.ID_Bhutan,
	"Bouvet Island":                 iso3162.ID_Bouvet_Island,
	"Botswana":                      iso3162.ID_Botswana,
	"Belarus":                       iso3162.ID_Belarus,
	"Belize":                        iso3162.ID_Belize,
	"Canada":                        iso3162.ID_Canada,
	"Cocos Islands":                 iso3162.ID_Cocos_Islands,
	"Congo, Democratic Republic of": iso3162.ID_Congo_Democratic_Republic_Of,
	"Central African Republic":      iso3162.ID_Central_African_Republic,
	"Congo":                         iso3162.ID_Congo,
	"Switzerland":                   iso3162.ID_Switzerland,
	"Cote d'Ivoire":                 iso3162.ID_Cote_d_Ivoire,
	"Cook Islands":                  iso3162.ID_Cook_Islands,
	"Chile":                         iso3162.ID_Chile,
	"Cameroon":                      iso3162.ID_Cameroon,
	"China":                         iso3162.ID_China,
	"Colombia":                      iso3162.ID_Colombia,
	"Costa Rica":                    iso3162.ID_Costa_Rica,
	"Cuba":                          iso3162.ID_Cuba,
	"Cabo Verde":                    iso3162.ID_Cabo_Verde,
	"Curacao":                       iso3162.ID_Curacao,
	"Christmas Island":              iso3162.ID_Christmas_Island,
	"Cyprus":                        iso3162.ID_Cyprus,
	"Czechia":                       iso3162.ID_Czechia,
	"Germany":                       iso3162.ID_Germany,
	"Djibouti":                      iso3162.ID_Djibouti,
	"Denmark":                       iso3162.ID_Denmark,
	"Dominica":                      iso3162.ID_Dominica,
	"Dominican Republic":            iso3162.ID_Dominican_Republic,
	"Algeria":                       iso3162.ID_Algeria,
	"Ecuador":                       iso3162.ID_Ecuador,
	"Estonia":                       iso3162.ID_Estonia,
	"Egypt":                         iso3162.ID_Egypt,
	"Western Sahara":                iso3162.ID_Western_Sahara,
	"Eritrea":                       iso3162.ID_Eritrea,
	"Spain":                         iso3162.ID_Spain,
	"Ethiopia":                      iso3162.ID_Ethiopia,
	"Finland":                       iso3162.ID_Finland,
	"Fiji":                          iso3162.ID_Fiji,
	"Falkland Islands":              iso3162.ID_Falkland_Islands,
	"Micronesia":                    iso3162.ID_Micronesia,
	"Faroe Islands":                 iso3162.ID_Faroe_Islands,
	"France":                        iso3162.ID_France,
	"Gabon":                         iso3162.ID_Gabon,
	"United Kingdom":                iso3162.ID_United_Kingdom,
	"Grenada":                       iso3162.ID_Grenada,
	"Georgia":                       iso3162.ID_Georgia,
	"French Guiana":                 iso3162.ID_French_Guiana,
	"Guernsey":                      iso3162.ID_Guernsey,
	"Ghana":                         iso3162.ID_Ghana,
	"Gibraltar":                     iso3162.ID_Gibraltar,
	"Greenland":                     iso3162.ID_Greenland,
	"Gambia":                        iso3162.ID_Gambia,
	"Guinea":                        iso3162.ID_Guinea,
	"Guadeloupe":                    iso3162.ID_Guadeloupe,
	"Equatorial Guinea":             iso3162.ID_Equatorial_Guinea,
	"Greece":                        iso3162.ID_Greece,
	"South Georgia and South Sandwich Islands": iso3162.ID_South_Georgia_And_South_Sandwich_Islands,
	"Guatemala":                         iso3162.ID_Guatemala,
	"Guam":                              iso3162.ID_Guam,
	"Guinea Bissau":                     iso3162.ID_Guinea_Bissau,
	"Guyana":                            iso3162.ID_Guyana,
	"Hong Kong":                         iso3162.ID_Hong_Kong,
	"Heard Island and McDonald Islands": iso3162.ID_Heard_Island_And_McDonald_Islands,
	"Honduras":                          iso3162.ID_Honduras,
	"Croatia":                           iso3162.ID_Croatia,
	"Haiti":                             iso3162.ID_Haiti,
	"Hungary":                           iso3162.ID_Hungary,
	"Indonesia":                         iso3162.ID_Indonesia,
	"Ireland":                           iso3162.ID_Ireland,
	"Israel":                            iso3162.ID_Israel,
	"Isle of Man":                       iso3162.ID_Isle_Of_Man,
	"India":                             iso3162.ID_India,
	"British Indian Ocean Territory":    iso3162.ID_British_Indian_Ocean_Territory,
	"Iraq":                              iso3162.ID_Iraq,
	"Iran":                              iso3162.ID_Iran,
	"Iceland":                           iso3162.ID_Iceland,
	"Italy":                             iso3162.ID_Italy,
	"Jersey":                            iso3162.ID_Jersey,
	"Jamaica":                           iso3162.ID_Jamaica,
	"Jordan":                            iso3162.ID_Jordan,
	"Japan":                             iso3162.ID_Japan,
	"Kenya":                             iso3162.ID_Kenya,
	"Kyrgyzstan":                        iso3162.ID_Kyrgyzstan,
	"Cambodia":                          iso3162.ID_Cambodia,
	"Kiribati":                          iso3162.ID_Kiribati,
	"Comoros":                           iso3162.ID_Comoros,
	"Saint Kitts and Nevis":             iso3162.ID_Saint_Kitts_And_Nevis,
	"North Korea":                       iso3162.ID_North_Korea,
	"South Korea":                       iso3162.ID_South_Korea,
	"Kuwait":                            iso3162.ID_Kuwait,
	"Cayman Islands":                    iso3162.ID_Cayman_Islands,
	"Kazakhstan":                        iso3162.ID_Kazakhstan,
	"Lao":                               iso3162.ID_Lao,
	"Lebanon":                           iso3162.ID_Lebanon,
	"Saint Lucia":                       iso3162.ID_Saint_Lucia,
	"Liechtenstein":                     iso3162.ID_Liechtenstein,
	"Sri Lanka":                         iso3162.ID_Sri_Lanka,
	"Liberia":                           iso3162.ID_Liberia,
	"Lesotho":                           iso3162.ID_Lesotho,
	"Lithuania":                         iso3162.ID_Lithuania,
	"Luxembourg":                        iso3162.ID_Luxembourg,
	"Latvia":                            iso3162.ID_Latvia,
	"Libya":                             iso3162.ID_Libya,
	"Morocco":                           iso3162.ID_Morocco,
	"Monaco":                            iso3162.ID_Monaco,
	"Moldova":                           iso3162.ID_Moldova,
	"Montenegro":                        iso3162.ID_Montenegro,
	"Saint Martin (French)":             iso3162.ID_Saint_Martin_French,
	"Madagascar":                        iso3162.ID_Madagascar,
	"Marshall Islands":                  iso3162.ID_Marshall_Islands,
	"North Macedonia":                   iso3162.ID_North_Macedonia,
	"Mali":                              iso3162.ID_Mali,
	"Myanmar":                           iso3162.ID_Myanmar,
	"Mongolia":                          iso3162.ID_Mongolia,
	"Macao":                             iso3162.ID_Macao,
	"Northern Mariana Islands":          iso3162.ID_Northern_Mariana_Islands,
	"Martinique":                        iso3162.ID_Martinique,
	"Mauritania":                        iso3162.ID_Mauritania,
	"Montserrat":                        iso3162.ID_Montserrat,
	"Malta":                             iso3162.ID_Malta,
	"Mauritius":                         iso3162.ID_Mauritius,
	"Maldives":                          iso3162.ID_Maldives,
	"Malawi":                            iso3162.ID_Malawi,
	"Mexico":                            iso3162.ID_Mexico,
	"Malaysia":                          iso3162.ID_Malaysia,
	"Mozambique":                        iso3162.ID_Mozambique,
	"Namibia":                           iso3162.ID_Namibia,
	"New Caledonia":                     iso3162.ID_New_Caledonia,
	"Niger":                             iso3162.ID_Niger,
	"Norfolk Island":                    iso3162.ID_Norfolk_Island,
	"Nigeria":                           iso3162.ID_Nigeria,
	"Nicaragua":                         iso3162.ID_Nicaragua,
	"Netherlands":                       iso3162.ID_Netherlands,
	"Norway":                            iso3162.ID_Norway,
	"Nepal":                             iso3162.ID_Nepal,
	"Nauru":                             iso3162.ID_Nauru,
	"Niue":                              iso3162.ID_Niue,
	"New Zealand":                       iso3162.ID_New_Zealand,
	"Oman":                              iso3162.ID_Oman,
	"Panama":                            iso3162.ID_Panama,
	"Peru":                              iso3162.ID_Peru,
	"French Polynesia":                  iso3162.ID_French_Polynesia,
	"Papua New Guinea":                  iso3162.ID_Papua_New_Guinea,
	"Philippines":                       iso3162.ID_Philippines,
	"Pakistan":                          iso3162.ID_Pakistan,
	"Poland":                            iso3162.ID_Poland,
	"Saint Pierre and Miquelon":         iso3162.ID_Saint_Pierre_And_Miquelon,
	"Pitcairn":                          iso3162.ID_Pitcairn,
	"Puerto Rico":                       iso3162.ID_Puerto_Rico,
	"Palestine":                         iso3162.ID_Palestine,
	"Portugal":                          iso3162.ID_Portugal,
	"Palau":                             iso3162.ID_Palau,
	"Paraguay":                          iso3162.ID_Paraguay,
	"Qatar":                             iso3162.ID_Qatar,
	"Russia":                            iso3162.ID_Russia,
	"Rwanda":                            iso3162.ID_Rwanda,
	"Saudi Arabia":                      iso3162.ID_Saudi_Arabia,
	"Solomon Islands":                   iso3162.ID_Solomon_Islands,
	"Seychelles":                        iso3162.ID_Seychelles,
	"Sudan":                             iso3162.ID_Sudan,
	"Sweden":                            iso3162.ID_Sweden,
	"Singapore":                         iso3162.ID_Singapore,
	"Saint Helena, Ascension and Tristan da Cunha": iso3162.ID_Saint_Helena_Ascension_And_Tristan_Da_Cunha,
	"Slovenia":                             iso3162.ID_Slovenia,
	"Svalbard and Jan Mayen":               iso3162.ID_Svalbard_And_Jan_Mayen,
	"Slovakia":                             iso3162.ID_Slovakia,
	"Sierra Leone":                         iso3162.ID_Sierra_Leone,
	"San Marino":                           iso3162.ID_San_Marino,
	"Senegal":                              iso3162.ID_Senegal,
	"Somalia":                              iso3162.ID_Somalia,
	"Suriname":                             iso3162.ID_Suriname,
	"South Sudan":                          iso3162.ID_South_Sudan,
	"Sao Tome and Principe":                iso3162.ID_Sao_Tome_And_Principe,
	"El Salvador":                          iso3162.ID_El_Salvador,
	"Sint Maarten (Dutch)":                 iso3162.ID_Sint_Maarten_Dutch,
	"Syria":                                iso3162.ID_Syria,
	"Eswatini":                             iso3162.ID_Eswatini,
	"Turks and Caicos Islands":             iso3162.ID_Turks_And_Caicos_Islands,
	"Chad":                                 iso3162.ID_Chad,
	"French Southern Territories":          iso3162.ID_French_Southern_Territories,
	"Togo":                                 iso3162.ID_Togo,
	"Thailand":                             iso3162.ID_Thailand,
	"Tajikistan":                           iso3162.ID_Tajikistan,
	"Tokelau":                              iso3162.ID_Tokelau,
	"Timor Leste":                          iso3162.ID_Timor_Leste,
	"Turkmenistan":                         iso3162.ID_Turkmenistan,
	"Tunisia":                              iso3162.ID_Tunisia,
	"Tonga":                                iso3162.ID_Tonga,
	"Turkey":                               iso3162.ID_Turkey,
	"Trinidad and Tobago":                  iso3162.ID_Trinidad_And_Tobago,
	"Tuvalu":                               iso3162.ID_Tuvalu,
	"Taiwan":                               iso3162.ID_Taiwan,
	"Tanzania":                             iso3162.ID_Tanzania,
	"Ukraine":                              iso3162.ID_Ukraine,
	"United States Minor Outlying Islands": iso3162.ID_United_States_Minor_Outlying_Islands,
	"United States":                        iso3162.ID_United_States,
	"Uruguay":                              iso3162.ID_Uruguay,
	"Uzbekistan":                           iso3162.ID_Uzbekistan,
	"Holy See":                             iso3162.ID_Holy_See,
	"Vatican":                              iso3162.ID_Vatican,
	"Saint Vincent and The Grenadines":     iso3162.ID_Saint_Vincent_And_The_Grenadines,
	"Venezuela":                            iso3162.ID_Venezuela,
	"Virgin Islands (British)":             iso3162.ID_Virgin_Islands_British,
	"Virgin Islands (US)":                  iso3162.ID_Virgin_Islands_US,
	"Vietnam":                              iso3162.ID_Vietnam,
	"Vanuatu":                              iso3162.ID_Vanuatu,
	"Wallis and Futuna":                    iso3162.ID_Wallis_And_Futuna,
	"Samoa":                                iso3162.ID_Samoa,
	"Yemen":                                iso3162.ID_Yemen,
	"Mayotte":                              iso3162.ID_Mayotte,
	"South Africa":                         iso3162.ID_South_Africa,
	"Zambia":                               iso3162.ID_Zambia,
	"Zimbabwe":                             iso3162.ID_Zimbabwe,
}

func GetID(name string) iso3162.ID {

	val, ok := ids[Name(strings.ToLower(name))]
	if !ok {
		return ids[""]
	}
	return val
}

func GetName(id iso3162.ID) Name {

	return names[id]
}
